name: drivers
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  get_it: ^7.2.0
  equatable: ^2.0.3
  localized_string: ^0.2.0
  ansicolor: ^2.0.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  dio: ^4.0.0
  bloc: ^7.2.1
  flutter_bloc: ^7.2.0
  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0
  mask_text_input_formatter: ^2.0.0
  email_validator: ^2.0.1
  uni_links: ^0.5.1
  url_launcher: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.0
  mockito: ^5.0.14
  build_runner: ^2.1.1
  flutter_lints: ^1.0.0
  app_lints:
    path: ../app_lints

flutter:
