name: debug_services

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  drivers:
    path: ../drivers
  config:
    path: ../config
  error_services:
    path: ../error_services
  common_ui_services:
    path: ../common_ui_services
  common_device_services:
    path: ../common_device_services
  package_info_plus: ^1.0.6
  alice: ^0.2.5
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  equatable: ^2.0.3
  overlay_support: ^1.2.1
  loggy: ^2.0.1+1
  flutter_loggy: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  app_lints:
    path: ../app_lints

flutter:
