name: drivers
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  get_it: ^7.2.0
  equatable: ^2.0.3
  ansicolor: ^2.0.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  dio: ^4.0.0
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  cached_network_image: ^3.1.0
  flutter_svg: ^1.0.3
  mask_text_input_formatter: ^2.0.0
  email_validator: ^2.0.1
  uni_links: ^0.5.1
  url_launcher: ^6.0.7
  serdes_json: ^0.4.0
  # serdes_json:
    # path: ../../../serdes_json_2/serdes_json
  loggy: ^2.0.1+1
  flutter_libphonenumber: ^1.0.4
  flutter_blurhash: ^0.6.6
  flutter_cache_manager: ^3.3.0
  image: ^3.1.3
  crypto: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.0
  mockito: ^5.0.14
  build_runner: ^2.1.1
  flutter_lints: ^1.0.0
  serdes_json_generator: ^0.4.3
  # serdes_json_generator:
    # path: ../../../serdes_json_2/serdes_json_generator
  app_lints:
    path: ../app_lints

flutter:
