name: common_device_services

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  drivers:
    path: ../drivers
  error_services:
    path: ../error_services
  sms_user_consent: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  app_lints:
    path: ../app_lints

flutter:
